#!/usr/bin/env python3
# Copyright (c) 2024-2026 MeedyaSuite
# Licensed under the MIT License. See LICENSE file in the project root.
"""
.github/scripts/test_check_lockfile_already_fixed.py

Tests for `check_lockfile_already_fixed.py`, the helper that tells
`forward-port-security.yml` whether a channel branch "already has" a
security fix that landed on `main`.

WHY THESE TESTS MATTER
----------------------
A wrong "already fixed" answer from the helper makes the workflow skip a
channel without a pull request or an issue, so a security fix silently
never reaches that channel. A wrong "needs the fix" only costs a pull
request or an issue that a person can close. Every test here pins down one
way the helper used to say "already fixed" when it could not know that, or
checks that it still says "already fixed" in the plain cases where it can.
Several are exact reproductions of the problems Codex found reviewing
pull request #1275; their names end in `_codex_finding_N`.

HOW THEY WORK
-------------
Each test builds a small, made-up lockfile (and sometimes a manifest) in a
throwaway git repository: a commit before the fix, the fix commit, and a
separate commit standing in for the channel branch. It then runs the real
helper as a separate program, exactly as the workflow does, and reads its
`RESULT=` line. Nothing touches the real repository or the network. Only
the Python standard library and `git` are needed.

Run:  python3 .github/scripts/test_check_lockfile_already_fixed.py

To watch these tests fail against an older copy of the helper, point
CHECK_LOCKFILE_HELPER at it:
    CHECK_LOCKFILE_HELPER=/path/to/old/check_lockfile_already_fixed.py \
        python3 .github/scripts/test_check_lockfile_already_fixed.py
"""

from __future__ import annotations

import json
import os
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

# The helper under test. Overridable so the same tests can be run against
# an older copy to show they fail there (see the module docstring).
HELPER = Path(
    os.environ.get("CHECK_LOCKFILE_HELPER")
    or Path(__file__).with_name("check_lockfile_already_fixed.py")
).resolve()

FIXED = "ALREADY_FIXED"
NEEDS = "NEEDS_PORT"

NPM_LOCK = "package-lock.json"
NPM_MANIFEST = "package.json"
CARGO_LOCK = "src-tauri/Cargo.lock"
CARGO_MANIFEST = "src-tauri/Cargo.toml"


def isolated_git_env() -> dict[str, str]:
    """An environment in which `git` ignores the user's and the machine's
    own settings (commit signing, hooks, a different default branch...), so
    the throwaway repositories behave the same on every machine and in CI."""
    env = dict(os.environ)
    env.update(
        {
            "GIT_CONFIG_GLOBAL": os.devnull,
            "GIT_CONFIG_NOSYSTEM": "1",
            "GIT_AUTHOR_NAME": "test",
            "GIT_AUTHOR_EMAIL": "test@example.invalid",
            "GIT_COMMITTER_NAME": "test",
            "GIT_COMMITTER_EMAIL": "test@example.invalid",
        }
    )
    return env


GIT_ENV = isolated_git_env()


# ---------------------------------------------------------------------------
# Small builders for made-up dependency files
# ---------------------------------------------------------------------------


def npm_lock(packages: dict[str, str | dict]) -> str:
    """A package-lock.json (lockfileVersion 3). `packages` maps each
    `node_modules/...` path to a version string, or to a full entry when a
    test needs extra fields such as an alias's real `name`."""
    entries: dict[str, dict] = {"": {"name": "demo", "version": "1.0.0"}}
    for key, value in packages.items():
        entries[key] = dict(value) if isinstance(value, dict) else {"version": value}
    document = {
        "name": "demo",
        "version": "1.0.0",
        "lockfileVersion": 3,
        "requires": True,
        "packages": entries,
    }
    return json.dumps(document, indent=2) + "\n"


def cargo_lock(crates: list[tuple[str, str]]) -> str:
    """A Cargo.lock with the project's own crate plus `crates`, each a
    (name, version) pair. The same name may appear more than once."""
    parts = [
        "# This file is automatically @generated by Cargo.\n"
        "# It is not intended for manual editing.\n"
        "version = 4\n"
        '\n[[package]]\nname = "demo"\nversion = "1.0.0"\n'
    ]
    for name, version in crates:
        parts.append(
            f'\n[[package]]\nname = "{name}"\nversion = "{version}"\n'
            'source = "registry+https://github.com/rust-lang/crates.io-index"\n'
        )
    return "".join(parts)


def package_json(overrides: list[tuple[str, str]]) -> str:
    """A package.json whose `overrides` block lists `overrides` in order.
    The last entry has no trailing comma, exactly as JSON requires — which
    is what makes the trailing-comma rule in the helper matter."""
    body = ",\n".join(f'    "{name}": "{spec}"' for name, spec in overrides)
    return '{\n  "name": "demo",\n  "version": "1.0.0",\n  "overrides": {\n' + body + "\n  }\n}\n"


def cargo_manifest(body: str) -> str:
    """A Cargo.toml with a fixed [package] table followed by `body`, written
    out by hand so a test can choose the exact table layout."""
    return '[package]\nname = "demo"\nversion = "1.0.0"\n\n' + body


def cargo_toml(dependency_lines: list[str]) -> str:
    return '[package]\nname = "demo"\nversion = "1.0.0"\n\n[dependencies]\n' + "".join(
        line + "\n" for line in dependency_lines
    )


# ---------------------------------------------------------------------------
# A throwaway git repository that makes commits without a working tree
# ---------------------------------------------------------------------------


class Repo:
    """Builds commits straight into the object store with `git fast-import`,
    so a test can say "this commit has exactly these files" with no
    checkout, no branch switching and nothing left lying around. (One
    fast-import per commit rather than a handful of plumbing commands per
    file: starting git is the slow part, and these tests make many commits.)"""

    def __init__(self, path: Path) -> None:
        self.path = path
        self.count = 0
        self.git("init", "-q", "-b", "main")

    def git(self, *args: str, input_bytes: bytes | None = None) -> str:
        result = subprocess.run(
            ["git", *args],
            cwd=self.path,
            input=input_bytes,
            capture_output=True,
            env=GIT_ENV,
            check=False,
        )
        if result.returncode != 0:
            raise RuntimeError(f"git {' '.join(args)} failed:\n{result.stderr.decode(errors='replace')}")
        return result.stdout.decode().strip()

    def commit(self, parent: str | None, files: dict[str, str | None], message: str = "test commit") -> str:
        """A new commit whose files are `parent`'s with `files` applied on
        top (a value of None deletes that file). `parent=None` starts from
        an empty tree, with no parent at all."""
        self.count += 1
        ref = f"refs/test/commit-{self.count}"  # a fresh ref each time, so nothing is overwritten
        stream = bytearray()

        def data(text: str) -> None:
            raw = text.encode()
            stream.extend(f"data {len(raw)}\n".encode() + raw + b"\n")

        stream.extend(f"commit {ref}\ncommitter test <test@example.invalid> 0 +0000\n".encode())
        data(message)
        if parent:
            stream.extend(f"from {parent}\n".encode())
        for name, content in files.items():
            if content is None:
                stream.extend(f"D {name}\n".encode())
            else:
                stream.extend(f"M 100644 inline {name}\n".encode())
                data(content)
        self.git("fast-import", "--quiet", input_bytes=bytes(stream))
        return self.git("rev-parse", ref)


class HelperTestCase(unittest.TestCase):
    """Shared set-up: one throwaway repository per test, and a `verdict`
    method that runs the real helper and insists on a clean answer."""

    def setUp(self) -> None:
        self.assertTrue(HELPER.is_file(), f"helper not found at {HELPER}")
        self._tmp = tempfile.TemporaryDirectory(prefix="lockfile-check-test-")
        self.repo = Repo(Path(self._tmp.name))

    def tearDown(self) -> None:
        self._tmp.cleanup()

    def fix(self, before: dict[str, str], changes: dict[str, str | None]) -> tuple[str, str]:
        """(commit before the fix, the fix commit)."""
        old = self.repo.commit(None, before, "before the fix")
        new = self.repo.commit(old, changes, "the fix")
        return old, new

    def branch(self, files: dict[str, str]) -> str:
        """A commit standing in for the channel branch being checked."""
        return self.repo.commit(None, files, "channel branch")

    def verdict(self, old: str, new: str, target: str, *paths: str, options: tuple[str, ...] = ()) -> str:
        """Run the helper; return ALREADY_FIXED or NEEDS_PORT. Fails the test
        if the helper crashed, printed no single RESULT line, or gave an exit
        code that disagrees with its RESULT line — a crash must never be
        mistaken for an answer."""
        result = subprocess.run(
            [
                sys.executable,
                str(HELPER),
                "--repo-root",
                str(self.repo.path),
                "--old",
                old,
                "--new",
                new,
                "--target",
                target,
                *options,
                *paths,
            ],
            capture_output=True,
            text=True,
            env=GIT_ENV,
            check=False,
        )
        shown = f"\nexit code: {result.returncode}\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
        results = [line for line in result.stdout.splitlines() if line.startswith("RESULT=")]
        self.assertEqual(len(results), 1, "the helper did not print exactly one RESULT line" + shown)
        answer = results[0].split("=", 1)[1]
        self.assertIn(answer, (FIXED, NEEDS), "unexpected RESULT value" + shown)
        self.assertEqual(result.returncode == 0, answer == FIXED, "exit code and RESULT disagree" + shown)
        self.last_output = result.stdout
        return answer

    def assertVerdict(self, expected: str, old: str, new: str, target: str, *paths: str, options: tuple[str, ...] = ()) -> None:
        answer = self.verdict(old, new, target, *paths, options=options)
        self.assertEqual(answer, expected, "helper output:\n" + self.last_output)


# ---------------------------------------------------------------------------
# Decision 1: every copy of a changed package counts
# ---------------------------------------------------------------------------


class EveryCopyCounts(HelperTestCase):
    def test_cargo_target_keeps_an_older_copy_codex_finding_1(self) -> None:
        # main moves `example` from 1.0.1 to 1.0.3. The channel already has
        # 1.0.3, but also still has 1.0.0 beside it. The old helper only
        # checked that 1.0.1 itself was gone and that some copy was new
        # enough, so it called this fixed.
        old, new = self.fix(
            {CARGO_LOCK: cargo_lock([("example", "1.0.1")])},
            {CARGO_LOCK: cargo_lock([("example", "1.0.3")])},
        )
        target = self.branch({CARGO_LOCK: cargo_lock([("example", "1.0.3"), ("example", "1.0.0")])})
        self.assertVerdict(NEEDS, old, new, target, CARGO_LOCK)

    def test_npm_target_keeps_a_nested_older_copy_codex_finding_1(self) -> None:
        # The channel's top-level copy is fixed, but a nested copy under
        # another package is still at the vulnerable 1.0.1. The old helper
        # only looked at the one path main had changed.
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.1"})},
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.3"})},
        )
        target = self.branch(
            {
                NPM_LOCK: npm_lock(
                    {
                        "node_modules/example": "1.0.3",
                        "node_modules/other/node_modules/example": "1.0.1",
                    }
                )
            }
        )
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK)

    def test_npm_copy_installed_under_another_name_still_counts(self) -> None:
        # npm can install a package under an alias ("x": "npm:example@1");
        # the entry then sits at node_modules/x and records its real name.
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.1"})},
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.3"})},
        )
        target = self.branch(
            {
                NPM_LOCK: npm_lock(
                    {
                        "node_modules/example": "1.0.3",
                        "node_modules/example-alias": {"name": "example", "version": "1.0.1"},
                    }
                )
            }
        )
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK)

    def test_npm_scoped_package_nested_older_copy(self) -> None:
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/@scope/example": "1.0.1"})},
            {NPM_LOCK: npm_lock({"node_modules/@scope/example": "1.0.3"})},
        )
        target = self.branch(
            {
                NPM_LOCK: npm_lock(
                    {
                        "node_modules/@scope/example": "1.0.3",
                        "node_modules/a/node_modules/@scope/example": "1.0.2",
                    }
                )
            }
        )
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK)

    def test_npm_copy_on_a_major_version_the_fix_did_not_touch_cannot_tell(self) -> None:
        # The fix only moved the 1.x copy. The channel also has a 2.x copy.
        # Nothing here says whether 2.0.0 is safe, so the helper must not
        # answer "already fixed".
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.1"})},
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.3"})},
        )
        target = self.branch(
            {
                NPM_LOCK: npm_lock(
                    {
                        "node_modules/example": "1.0.3",
                        "node_modules/other/node_modules/example": "2.0.0",
                    }
                )
            }
        )
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK)

    def test_cargo_copy_on_another_zero_x_line_cannot_tell(self) -> None:
        # For versions below 1.0, each 0.x is its own release line.
        old, new = self.fix(
            {CARGO_LOCK: cargo_lock([("h2", "0.4.15")])},
            {CARGO_LOCK: cargo_lock([("h2", "0.4.18")])},
        )
        target = self.branch({CARGO_LOCK: cargo_lock([("h2", "0.4.18"), ("h2", "0.3.26")])})
        self.assertVerdict(NEEDS, old, new, target, CARGO_LOCK)

    def test_every_copy_at_or_above_the_fix_is_already_fixed(self) -> None:
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.1"})},
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.3"})},
        )
        target = self.branch(
            {
                NPM_LOCK: npm_lock(
                    {
                        "node_modules/example": "1.0.3",
                        "node_modules/other/node_modules/example": "1.0.4",
                    }
                )
            }
        )
        self.assertVerdict(FIXED, old, new, target, NPM_LOCK)

        old, new = self.fix(
            {CARGO_LOCK: cargo_lock([("example", "1.0.1")])},
            {CARGO_LOCK: cargo_lock([("example", "1.0.3")])},
        )
        target = self.branch({CARGO_LOCK: cargo_lock([("example", "1.0.3"), ("example", "1.4.0")])})
        self.assertVerdict(FIXED, old, new, target, CARGO_LOCK)

    def test_target_newer_than_the_fix_is_already_fixed(self) -> None:
        old, new = self.fix(
            {CARGO_LOCK: cargo_lock([("example", "1.0.1")])},
            {CARGO_LOCK: cargo_lock([("example", "1.0.3")])},
        )
        target = self.branch({CARGO_LOCK: cargo_lock([("example", "1.2.0")])})
        self.assertVerdict(FIXED, old, new, target, CARGO_LOCK)

    def test_target_behind_the_fix_needs_the_fix(self) -> None:
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.1"})},
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.3"})},
        )
        target = self.branch({NPM_LOCK: npm_lock({"node_modules/example": "1.0.2"})})
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK)

    def test_a_fix_that_moves_a_version_down_cannot_tell(self) -> None:
        # Moving to an OLDER version (a bad release withdrawn, say) is not
        # something "at or above" can describe: the channel's 1.0.5 is
        # "above" 1.0.4 and is exactly what the fix took away.
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.5"})},
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.4"})},
        )
        target = self.branch({NPM_LOCK: npm_lock({"node_modules/example": "1.0.5"})})
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK)

    def test_pre_release_labels_that_cannot_be_ordered_need_the_fix(self) -> None:
        # "beta.2" sorts after "beta.10" as plain text but before it as a
        # version. The helper does not order pre-release labels, so it must
        # not guess "already fixed".
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.3-beta.1"})},
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.3-beta.10"})},
        )
        target = self.branch({NPM_LOCK: npm_lock({"node_modules/example": "1.0.3-beta.2"})})
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK)

    def test_cargo_block_with_version_not_straight_after_name_is_still_read(self) -> None:
        # The earlier reader only saw a crate when `version` sat on the line
        # straight after `name`, and silently dropped any other block. Here
        # the fix removes `evil`, and the channel still has it, written with
        # `source` between the two lines: dropping that block made the fix
        # look done.
        old, new = self.fix(
            {CARGO_LOCK: cargo_lock([("example", "1.0.1"), ("evil", "1.0.0")])},
            {CARGO_LOCK: cargo_lock([("example", "1.0.1")])},
        )
        target = self.branch(
            {
                CARGO_LOCK: cargo_lock([("example", "1.0.1")])
                + '\n[[package]]\nname = "evil"\n'
                'source = "registry+https://github.com/rust-lang/crates.io-index"\nversion = "1.0.0"\n'
            }
        )
        self.assertVerdict(NEEDS, old, new, target, CARGO_LOCK)

    def test_cargo_block_without_a_version_cannot_tell(self) -> None:
        old, new = self.fix(
            {CARGO_LOCK: cargo_lock([("example", "1.0.1")])},
            {CARGO_LOCK: cargo_lock([("example", "1.0.3")])},
        )
        target = self.branch({CARGO_LOCK: cargo_lock([("example", "1.0.3")]) + '\n[[package]]\nname = "example"\n'})
        self.assertVerdict(NEEDS, old, new, target, CARGO_LOCK)

    def test_a_copy_whose_version_cannot_be_read_cannot_tell(self) -> None:
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.1"})},
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.3"})},
        )
        target = self.branch(
            {
                NPM_LOCK: npm_lock(
                    {
                        "node_modules/example": "1.0.3",
                        "node_modules/other/node_modules/example": {"resolved": "file:../example"},
                    }
                )
            }
        )
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK)


# ---------------------------------------------------------------------------
# Decision 2: packages the fix added or removed count
# ---------------------------------------------------------------------------


class AddedAndRemovedPackagesCount(HelperTestCase):
    def test_npm_added_package_missing_on_target_codex_finding_2(self) -> None:
        # The fix bumps `example` AND adds `security-helper`. The channel
        # has the bump but not the new package. The old helper only looked
        # at packages present on both sides of the fix, so it never noticed.
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.1"})},
            {
                NPM_LOCK: npm_lock(
                    {"node_modules/example": "1.0.3", "node_modules/security-helper": "2.0.0"}
                )
            },
        )
        target = self.branch({NPM_LOCK: npm_lock({"node_modules/example": "1.0.3"})})
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK)

    def test_npm_added_package_present_at_or_above_is_already_fixed(self) -> None:
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.1"})},
            {
                NPM_LOCK: npm_lock(
                    {"node_modules/example": "1.0.3", "node_modules/security-helper": "2.0.0"}
                )
            },
        )
        target = self.branch(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.3", "node_modules/security-helper": "2.1.0"})}
        )
        self.assertVerdict(FIXED, old, new, target, NPM_LOCK)

    def test_npm_added_package_present_but_older_needs_the_fix(self) -> None:
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.1"})},
            {
                NPM_LOCK: npm_lock(
                    {"node_modules/example": "1.0.3", "node_modules/security-helper": "2.0.5"}
                )
            },
        )
        target = self.branch(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.3", "node_modules/security-helper": "2.0.1"})}
        )
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK)

    def test_cargo_added_crate_missing_on_target_needs_the_fix(self) -> None:
        old, new = self.fix(
            {CARGO_LOCK: cargo_lock([("example", "1.0.1")])},
            {CARGO_LOCK: cargo_lock([("example", "1.0.3"), ("security-helper", "2.0.0")])},
        )
        target = self.branch({CARGO_LOCK: cargo_lock([("example", "1.0.3")])})
        self.assertVerdict(NEEDS, old, new, target, CARGO_LOCK)

    def test_npm_removed_package_still_nested_on_target_needs_the_fix(self) -> None:
        # The fix removes `evil` outright. The channel no longer has it at
        # the top level, but still has a nested copy.
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.1", "node_modules/evil": "1.0.0"})},
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.1"})},
        )
        target = self.branch(
            {
                NPM_LOCK: npm_lock(
                    {"node_modules/example": "1.0.1", "node_modules/example/node_modules/evil": "1.0.0"}
                )
            }
        )
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK)

    def test_cargo_removed_crate_still_on_target_at_another_version_needs_the_fix(self) -> None:
        old, new = self.fix(
            {CARGO_LOCK: cargo_lock([("example", "1.0.1"), ("evil", "1.0.0")])},
            {CARGO_LOCK: cargo_lock([("example", "1.0.1")])},
        )
        target = self.branch({CARGO_LOCK: cargo_lock([("example", "1.0.1"), ("evil", "1.2.0")])})
        self.assertVerdict(NEEDS, old, new, target, CARGO_LOCK)

    def test_removed_package_gone_from_target_is_already_fixed(self) -> None:
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.1", "node_modules/evil": "1.0.0"})},
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.1"})},
        )
        target = self.branch({NPM_LOCK: npm_lock({"node_modules/example": "1.0.2"})})
        self.assertVerdict(FIXED, old, new, target, NPM_LOCK)

        old, new = self.fix(
            {CARGO_LOCK: cargo_lock([("example", "1.0.1"), ("evil", "1.0.0")])},
            {CARGO_LOCK: cargo_lock([("example", "1.0.1")])},
        )
        target = self.branch({CARGO_LOCK: cargo_lock([("example", "1.0.1")])})
        self.assertVerdict(FIXED, old, new, target, CARGO_LOCK)

    def test_target_without_a_lockfile_cannot_confirm_a_removal(self) -> None:
        # The old helper read a missing channel Cargo.lock as "no crates at
        # all", so a fix that only REMOVED a crate looked "already fixed".
        old, new = self.fix(
            {CARGO_LOCK: cargo_lock([("example", "1.0.1"), ("evil", "1.0.0")])},
            {CARGO_LOCK: cargo_lock([("example", "1.0.1")])},
        )
        target = self.branch({"README.md": "no lockfile on this branch\n"})
        self.assertVerdict(NEEDS, old, new, target, CARGO_LOCK)


# ---------------------------------------------------------------------------
# Decision 3: the shortcut never skips a change it did not check
# ---------------------------------------------------------------------------

MANIFEST_OPTIONS = ("--manifest", NPM_MANIFEST, "--manifest", CARGO_MANIFEST)


class ShortcutOnlySkipsWhatItChecked(HelperTestCase):
    def cargo_feature_case(self) -> tuple[str, str, str]:
        """Codex's case: the fix turns off an unsafe Cargo feature AND bumps
        a crate. The channel already has the bumped crate (its own update
        run got there first) but still turns the unsafe feature on."""
        unsafe = cargo_toml(['foo = { version = "1", features = ["unsafe-feature"] }', 'bar = "0.4"'])
        safe = cargo_toml(['foo = { version = "1", default-features = false }', 'bar = "0.4"'])
        old, new = self.fix(
            {CARGO_MANIFEST: unsafe, CARGO_LOCK: cargo_lock([("foo", "1.2.0"), ("bar", "0.4.15")])},
            {CARGO_MANIFEST: safe, CARGO_LOCK: cargo_lock([("foo", "1.2.0"), ("bar", "0.4.18")])},
        )
        target = self.branch(
            {CARGO_MANIFEST: unsafe, CARGO_LOCK: cargo_lock([("foo", "1.2.0"), ("bar", "0.4.18")])}
        )
        return old, new, target

    def test_cargo_feature_change_with_a_bump_needs_the_fix_codex_finding_3(self) -> None:
        old, new, target = self.cargo_feature_case()
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK, CARGO_LOCK, options=MANIFEST_OPTIONS)

    def test_a_manifest_not_named_as_one_counts_as_another_file_codex_finding_3(self) -> None:
        # Called the way the old workflow called it (lockfiles only), the
        # changed Cargo.toml must now count as a file the check cannot see.
        old, new, target = self.cargo_feature_case()
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK, CARGO_LOCK)

    def test_any_other_changed_file_needs_the_fix(self) -> None:
        old, new = self.fix(
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.1"}), "src/app.ts": "export const x = 1;\n"},
            {NPM_LOCK: npm_lock({"node_modules/example": "1.0.3"}), "src/app.ts": "export const x = 2;\n"},
        )
        target = self.branch({NPM_LOCK: npm_lock({"node_modules/example": "1.0.3"})})
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK, CARGO_LOCK, options=MANIFEST_OPTIONS)

    def test_manifest_lines_already_on_target_is_already_fixed(self) -> None:
        # The shape of main's real undici fix: the changed override is the
        # LAST entry (no trailing comma); on the channel it is followed by
        # another entry (so it has one). Commas aside, the lines match.
        old, new = self.fix(
            {
                NPM_MANIFEST: package_json([("nanoid", "^3.3.17"), ("undici", "^7.29.0")]),
                NPM_LOCK: npm_lock({"node_modules/undici": "7.29.0"}),
            },
            {
                NPM_MANIFEST: package_json([("nanoid", "^3.3.17"), ("undici", "^7.30.0")]),
                NPM_LOCK: npm_lock({"node_modules/undici": "7.30.0"}),
            },
        )
        target = self.branch(
            {
                NPM_MANIFEST: package_json([("undici", "^7.30.0"), ("zod", "^4.0.0")]),
                NPM_LOCK: npm_lock({"node_modules/undici": "7.30.0"}),
            }
        )
        self.assertVerdict(FIXED, old, new, target, NPM_LOCK, CARGO_LOCK, options=MANIFEST_OPTIONS)

    def test_manifest_added_line_missing_on_target_needs_the_fix(self) -> None:
        old, new = self.fix(
            {
                NPM_MANIFEST: package_json([("undici", "^7.29.0")]),
                NPM_LOCK: npm_lock({"node_modules/undici": "7.29.0"}),
            },
            {
                NPM_MANIFEST: package_json([("undici", "^7.30.0")]),
                NPM_LOCK: npm_lock({"node_modules/undici": "7.30.0"}),
            },
        )
        # The lockfile is fixed, but the override that keeps it there is not.
        target = self.branch(
            {
                NPM_MANIFEST: package_json([("nanoid", "^3.3.17")]),
                NPM_LOCK: npm_lock({"node_modules/undici": "7.30.0"}),
            }
        )
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK, CARGO_LOCK, options=MANIFEST_OPTIONS)

    def test_manifest_removed_line_still_on_target_needs_the_fix(self) -> None:
        old, new = self.fix(
            {
                NPM_MANIFEST: package_json([("undici", "^7.29.0"), ("risky", "1.0.0")]),
                NPM_LOCK: npm_lock({"node_modules/undici": "7.29.0"}),
            },
            {
                NPM_MANIFEST: package_json([("undici", "^7.30.0")]),
                NPM_LOCK: npm_lock({"node_modules/undici": "7.30.0"}),
            },
        )
        target = self.branch(
            {
                NPM_MANIFEST: package_json([("undici", "^7.30.0"), ("risky", "1.0.0")]),
                NPM_LOCK: npm_lock({"node_modules/undici": "7.30.0"}),
            }
        )
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK, CARGO_LOCK, options=MANIFEST_OPTIONS)

    def test_target_without_the_manifest_needs_the_fix(self) -> None:
        old, new = self.fix(
            {
                NPM_MANIFEST: package_json([("undici", "^7.29.0")]),
                NPM_LOCK: npm_lock({"node_modules/undici": "7.29.0"}),
            },
            {
                NPM_MANIFEST: package_json([("undici", "^7.30.0")]),
                NPM_LOCK: npm_lock({"node_modules/undici": "7.30.0"}),
            },
        )
        target = self.branch({NPM_LOCK: npm_lock({"node_modules/undici": "7.30.0"})})
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK, CARGO_LOCK, options=MANIFEST_OPTIONS)

    def test_no_lockfile_change_needs_the_fix(self) -> None:
        old, new = self.fix(
            {NPM_MANIFEST: package_json([("undici", "^7.29.0")])},
            {NPM_MANIFEST: package_json([("undici", "^7.30.0")])},
        )
        target = self.branch({NPM_MANIFEST: package_json([("undici", "^7.30.0")])})
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK, CARGO_LOCK, options=MANIFEST_OPTIONS)

    def test_plain_dependabot_shaped_fix_on_a_fixed_branch_is_already_fixed(self) -> None:
        # The ordinary case the shortcut exists for (main's real brace-
        # expansion fix): one override line and one lockfile entry, and the
        # channel already has both. This must keep working.
        old, new = self.fix(
            {
                NPM_MANIFEST: package_json([("basic-ftp", "^5.3.1"), ("brace-expansion", "^5.0.9"), ("undici", "^7.30.0")]),
                NPM_LOCK: npm_lock({"node_modules/brace-expansion": "5.0.9"}),
            },
            {
                NPM_MANIFEST: package_json([("basic-ftp", "^5.3.1"), ("brace-expansion", "^5.0.12"), ("undici", "^7.30.0")]),
                NPM_LOCK: npm_lock({"node_modules/brace-expansion": "5.0.12"}),
            },
        )
        target = self.branch(
            {
                NPM_MANIFEST: package_json([("brace-expansion", "^5.0.12"), ("undici", "^7.30.0")]),
                NPM_LOCK: npm_lock({"node_modules/brace-expansion": "5.0.12"}),
            }
        )
        self.assertVerdict(FIXED, old, new, target, NPM_LOCK, CARGO_LOCK, options=MANIFEST_OPTIONS)


# ---------------------------------------------------------------------------
# Decision A (Codex's second review): manifests are compared as data
# ---------------------------------------------------------------------------

LOCK_BEFORE = cargo_lock([("baz", "0.4.15")])
LOCK_AFTER = cargo_lock([("baz", "0.4.18")])


class ManifestsComparedAsData(HelperTestCase):
    """Which dependency a setting belongs to matters. A loose line match
    cannot see that; comparing each dependency entry by its position can."""

    def cargo_case(self, before: str, after: str, channel: str) -> str:
        """Run the helper on a fix that changes Cargo.toml from `before` to
        `after` and bumps a crate, against a channel that already has the
        bump and whose Cargo.toml is `channel`."""
        old, new = self.fix(
            {CARGO_MANIFEST: cargo_manifest(before), CARGO_LOCK: LOCK_BEFORE},
            {CARGO_MANIFEST: cargo_manifest(after), CARGO_LOCK: LOCK_AFTER},
        )
        target = self.branch({CARGO_MANIFEST: channel, CARGO_LOCK: LOCK_AFTER})
        return self.verdict(old, new, target, NPM_LOCK, CARGO_LOCK, options=MANIFEST_OPTIONS)

    def test_setting_under_another_dependency_does_not_count_codex_review_2_finding_1(self) -> None:
        # Codex's case: the fix turns `foo`'s default features off. The
        # channel leaves them on for `foo`, and has `default-features =
        # false` under `bar` instead. Line by line, the added line "is there"
        # and the removed line "is gone".
        answer = self.cargo_case(
            '[dependencies.foo]\nversion = "1"\ndefault-features = true\n\n[dependencies.bar]\nversion = "2"\n',
            '[dependencies.foo]\nversion = "1"\ndefault-features = false\n\n[dependencies.bar]\nversion = "2"\n',
            cargo_manifest('[dependencies.foo]\nversion = "1"\n\n[dependencies.bar]\nversion = "2"\ndefault-features = false\n'),
        )
        self.assertEqual(answer, NEEDS, self.last_output)

    def test_same_entry_under_another_table_does_not_count(self) -> None:
        # The fix changes the Windows-only entry; the channel has the new
        # value, but under the everyday [dependencies] table.
        answer = self.cargo_case(
            "[target.'cfg(windows)'.dependencies]\nfoo = \"1.1\"\n",
            "[target.'cfg(windows)'.dependencies]\nfoo = \"1.2\"\n",
            cargo_manifest('[dependencies]\nfoo = "1.2"\n'),
        )
        self.assertEqual(answer, NEEDS, self.last_output)

    def test_removed_entry_still_present_in_another_form_needs_the_fix(self) -> None:
        answer = self.cargo_case(
            '[dependencies]\nfoo = "1"\nrisky = "1"\n',
            '[dependencies]\nfoo = "1"\n',
            cargo_manifest('[dependencies]\nfoo = "1"\nrisky = { version = "1" }\n'),
        )
        self.assertEqual(answer, NEEDS, self.last_output)

    def test_a_change_outside_the_dependency_tables_needs_the_fix(self) -> None:
        # Only dependency entries can be checked. A build setting the fix
        # changed is something else, so the shortcut must step aside even
        # when a matching line happens to sit elsewhere on the channel.
        answer = self.cargo_case(
            '[dependencies]\nfoo = "1"\n\n[profile.release]\noverflow-checks = false\n',
            '[dependencies]\nfoo = "1"\n\n[profile.release]\noverflow-checks = true\n',
            cargo_manifest('[dependencies]\nfoo = "1"\n\n[profile.dev]\noverflow-checks = true\n'),
        )
        self.assertEqual(answer, NEEDS, self.last_output)

    def test_a_channel_manifest_that_does_not_parse_needs_the_fix(self) -> None:
        answer = self.cargo_case(
            '[dependencies]\nfoo = "1.1"\n',
            '[dependencies]\nfoo = "1.2"\n',
            cargo_manifest('[dependencies]\nfoo = "1.2"\n[[[not toml\n'),
        )
        self.assertEqual(answer, NEEDS, self.last_output)

    def test_patch_entry_must_match_on_the_channel(self) -> None:
        before = '[dependencies]\nfoo = "1"\n'
        after = before + '\n[patch.crates-io]\nfoo = { git = "https://example.invalid/foo", rev = "abc123" }\n'
        self.assertEqual(self.cargo_case(before, after, cargo_manifest(before)), NEEDS, self.last_output)
        self.assertEqual(self.cargo_case(before, after, cargo_manifest(after)), FIXED, self.last_output)

    def test_the_same_entry_written_another_way_is_already_fixed(self) -> None:
        # Data, not text: an inline table and a [dependencies.foo] table with
        # the same contents are the same entry.
        answer = self.cargo_case(
            '[dependencies]\nfoo = { version = "1.1" }\n',
            '[dependencies]\nfoo = { version = "1.2", default-features = false }\n',
            cargo_manifest('[dependencies.foo]\nversion = "1.2"\ndefault-features = false\n'),
        )
        self.assertEqual(answer, FIXED, self.last_output)

    # --- settings a dependency takes from [workspace.dependencies] ----------

    WS_PLAIN = '[workspace.dependencies]\nfoo = { version = "1" }\n'
    WS_RISKY = '[workspace.dependencies]\nfoo = { version = "1", features = ["risky"] }\n'

    def test_inherited_workspace_settings_must_match_codex_review_4(self) -> None:
        # Codex's case: the fix drops `risky` from foo's own features. foo
        # also takes settings from [workspace.dependencies], and Cargo adds
        # the two feature lists together. The channel's local entry matches
        # the fix, but its workspace entry still turns `risky` on.
        answer = self.cargo_case(
            self.WS_PLAIN + '\n[dependencies]\nfoo = { workspace = true, features = ["risky"] }\n',
            self.WS_PLAIN + '\n[dependencies]\nfoo = { workspace = true, features = [] }\n',
            cargo_manifest(self.WS_RISKY + '\n[dependencies]\nfoo = { workspace = true, features = [] }\n'),
        )
        self.assertEqual(answer, NEEDS, self.last_output)

    def test_matching_inherited_workspace_settings_is_already_fixed(self) -> None:
        answer = self.cargo_case(
            self.WS_PLAIN + '\n[dependencies]\nfoo = { workspace = true, features = ["risky"] }\n',
            self.WS_PLAIN + '\n[dependencies]\nfoo = { workspace = true, features = [] }\n',
            cargo_manifest(self.WS_PLAIN + '\n[dependencies]\nfoo = { workspace = true, features = [] }\n'),
        )
        self.assertEqual(answer, FIXED, self.last_output)

    def test_inherited_entry_without_its_workspace_table_cannot_tell(self) -> None:
        # A workspace member: its [workspace.dependencies] table lives in
        # another Cargo.toml, which this check does not read.
        answer = self.cargo_case(
            '[dependencies]\nfoo = { workspace = true, features = ["risky"] }\n',
            '[dependencies]\nfoo = { workspace = true, features = [] }\n',
            cargo_manifest('[dependencies]\nfoo = { workspace = true, features = [] }\n'),
        )
        self.assertEqual(answer, NEEDS, self.last_output)
        self.assertIn("could not be checked", self.last_output)

    def test_inherited_entry_missing_from_the_channels_workspace_table_cannot_tell(self) -> None:
        answer = self.cargo_case(
            self.WS_PLAIN + '\n[target.\'cfg(windows)\'.dependencies]\nfoo = { workspace = true, features = ["risky"] }\n',
            self.WS_PLAIN + '\n[target.\'cfg(windows)\'.dependencies]\nfoo = { workspace = true }\n',
            cargo_manifest('[workspace]\nmembers = []\n\n[target.\'cfg(windows)\'.dependencies]\nfoo = { workspace = true }\n'),
        )
        self.assertEqual(answer, NEEDS, self.last_output)

    # --- everything a manifest says about a touched package is compared -----

    def test_channel_re_adds_what_the_workspace_fix_removed_stand_in_review_finding_1(self) -> None:
        # The mirror of Codex's case: the fix drops `risky` from the
        # workspace entry. The channel's workspace entry matches, but its own
        # [dependencies] entry switches `risky` back on.
        answer = self.cargo_case(
            self.WS_RISKY + '\n[dependencies]\nfoo = { workspace = true }\n',
            self.WS_PLAIN + '\n[dependencies]\nfoo = { workspace = true }\n',
            cargo_manifest(self.WS_PLAIN + '\n[dependencies]\nfoo = { workspace = true, features = ["risky"] }\n'),
        )
        self.assertEqual(answer, NEEDS, self.last_output)

    def test_channel_re_adds_it_in_a_platform_table_stand_in_review_finding_1(self) -> None:
        answer = self.cargo_case(
            self.WS_RISKY + '\n[dependencies]\nfoo = { workspace = true }\n',
            self.WS_PLAIN + '\n[dependencies]\nfoo = { workspace = true }\n',
            cargo_manifest(
                self.WS_PLAIN + '\n[dependencies]\nfoo = { workspace = true }\n'
                "\n[target.'cfg(windows)'.dependencies]\nfoo = { workspace = true, features = [\"risky\"] }\n"
            ),
        )
        self.assertEqual(answer, NEEDS, self.last_output)

    def test_another_table_on_the_channel_still_enables_it_stand_in_review_finding_2(self) -> None:
        answer = self.cargo_case(
            '[dependencies]\nfoo = { version = "1", features = ["risky"] }\n',
            '[dependencies]\nfoo = { version = "1", features = [] }\n',
            cargo_manifest(
                '[dependencies]\nfoo = { version = "1", features = [] }\n'
                "\n[target.'cfg(windows)'.dependencies]\nfoo = { version = \"1\", features = [\"risky\"] }\n"
            ),
        )
        self.assertEqual(answer, NEEDS, self.last_output)

    def test_a_feature_on_the_channel_still_enables_it_stand_in_review_finding_2(self) -> None:
        answer = self.cargo_case(
            '[dependencies]\nfoo = { version = "1", features = ["risky"] }\n',
            '[dependencies]\nfoo = { version = "1", features = [] }\n',
            cargo_manifest('[dependencies]\nfoo = { version = "1", features = [] }\n\n[features]\ndefault = ["foo/risky"]\n'),
        )
        self.assertEqual(answer, NEEDS, self.last_output)

    def test_every_mention_matching_is_already_fixed(self) -> None:
        after = '[dependencies]\nfoo = { version = "1", features = [] }\n\n[features]\ndefault = ["foo/std", "dep:foo"]\n'
        answer = self.cargo_case(
            '[dependencies]\nfoo = { version = "1", features = ["risky"] }\n\n[features]\ndefault = ["foo/std", "dep:foo"]\n',
            after,
            cargo_manifest(after),
        )
        self.assertEqual(answer, FIXED, self.last_output)

    def test_a_renamed_dependency_counts_as_the_same_package(self) -> None:
        # `bar = { package = "foo" }` is foo under another name. The channel
        # matches the renamed entry but still has foo 1.1 for its tests.
        answer = self.cargo_case(
            '[dependencies]\nbar = { package = "foo", version = "1.1" }\n',
            '[dependencies]\nbar = { package = "foo", version = "1.2" }\n',
            cargo_manifest('[dependencies]\nbar = { package = "foo", version = "1.2" }\n\n[dev-dependencies]\nfoo = "1.1"\n'),
        )
        self.assertEqual(answer, NEEDS, self.last_output)

    def test_an_entry_that_cannot_be_classified_needs_the_fix(self) -> None:
        answer = self.cargo_case(
            '[dependencies]\nfoo = "1.1"\n',
            '[dependencies]\nfoo = "1.2"\n',
            cargo_manifest('[dependencies]\nfoo = "1.2"\n\n[dev-dependencies]\nfoo = { package = 5 }\n'),
        )
        self.assertEqual(answer, NEEDS, self.last_output)

    def test_npm_channel_pins_the_package_again_in_a_nested_override(self) -> None:
        def manifest(overrides: dict) -> str:
            return json.dumps({"name": "demo", "version": "1.0.0", "overrides": overrides}, indent=2) + "\n"

        old, new = self.fix(
            {NPM_MANIFEST: manifest({"foo": "^1.0.1"}), NPM_LOCK: npm_lock({"node_modules/foo": "1.0.1"})},
            {NPM_MANIFEST: manifest({"foo": "^1.0.3"}), NPM_LOCK: npm_lock({"node_modules/foo": "1.0.3"})},
        )
        target = self.branch(
            {
                NPM_MANIFEST: manifest({"foo": "^1.0.3", "bar": {"foo": "1.0.1"}}),
                NPM_LOCK: npm_lock({"node_modules/foo": "1.0.3"}),
            }
        )
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK, CARGO_LOCK, options=MANIFEST_OPTIONS)

    def test_npm_nested_override_must_match_exactly(self) -> None:
        # The fix pins `bar` inside `foo`'s override. The channel has that
        # pin under a different package's override, and not under `foo`.
        def manifest(overrides: dict) -> str:
            return json.dumps({"name": "demo", "version": "1.0.0", "overrides": overrides}, indent=2) + "\n"

        old, new = self.fix(
            {NPM_MANIFEST: manifest({"foo": {"bar": "1.0.1"}}), NPM_LOCK: npm_lock({"node_modules/bar": "1.0.1"})},
            {NPM_MANIFEST: manifest({"foo": {"bar": "1.0.3"}}), NPM_LOCK: npm_lock({"node_modules/bar": "1.0.3"})},
        )
        target = self.branch(
            {
                NPM_MANIFEST: manifest({"foo": {"baz": "9.0.0"}, "qux": {"bar": "1.0.3"}}),
                NPM_LOCK: npm_lock({"node_modules/bar": "1.0.3"}),
            }
        )
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK, CARGO_LOCK, options=MANIFEST_OPTIONS)

    def test_npm_change_outside_the_dependency_sections_needs_the_fix(self) -> None:
        def manifest(script: str) -> str:
            return json.dumps({"name": "demo", "scripts": {"postinstall": script}, "overrides": {"bar": "^1.0.3"}}, indent=2) + "\n"

        old, new = self.fix(
            {NPM_MANIFEST: manifest("node setup.js --unsafe"), NPM_LOCK: npm_lock({"node_modules/bar": "1.0.1"})},
            {NPM_MANIFEST: manifest("node setup.js"), NPM_LOCK: npm_lock({"node_modules/bar": "1.0.3"})},
        )
        # The channel's install script is still unsafe (in another way); the
        # fix's new line sits under `config` instead, where it does nothing.
        channel = json.dumps(
            {
                "name": "demo",
                "scripts": {"postinstall": "node setup.js --also-unsafe"},
                "config": {"postinstall": "node setup.js"},
                "overrides": {"bar": "^1.0.3"},
            },
            indent=2,
        ) + "\n"
        target = self.branch({NPM_MANIFEST: channel, NPM_LOCK: npm_lock({"node_modules/bar": "1.0.3"})})
        self.assertVerdict(NEEDS, old, new, target, NPM_LOCK, CARGO_LOCK, options=MANIFEST_OPTIONS)


if __name__ == "__main__":
    unittest.main(verbosity=2)
