// Copyright (c) 2026 MeedyaSuite
// Licensed under the MIT License. See LICENSE file in the project root.

//! Diagnostic bundle composer (#572 Phase 1 MVP).
//!
//! Produces a redacted Markdown report covering MeedyaDL's system
//! state at the moment of capture — version info, settings snapshot,
//! recent activity-log slice, output-dir structure — for pasting into
//! GitHub issues during troubleshooting.
//!
//! ## Privacy contract (non-negotiable)
//!
//! - **No credentials**. The settings snapshot uses `redact_settings`
//!   which hard-filters every credential field
//!   (`musickit_team_id`, `musickit_key_id`, `cookies_path`,
//!   `wrapper_account_url` query params, …) and replaces them with
//!   `<redacted>` markers. The bundle composer NEVER touches the OS
//!   keychain.
//! - **No file contents**. The output-dir listing is metadata only
//!   (filenames + sizes), not contents. Audio / artwork / lyrics are
//!   never read.
//! - **No auto-submit**. The composer returns a Markdown string; the
//!   caller is responsible for showing it to the user for review and
//!   for the explicit "submit to GitHub" action.
//! - **Path username redaction**. `/Users/{name}/…` and
//!   `/home/{name}/…` become `/Users/{user}/…` / `/home/{user}/…` so
//!   the bundle doesn't leak the operator's account name.
//!
//! ## What's in scope for Phase 1
//!
//! - Version info (MeedyaDL + GAMDL + Python + tools).
//! - Settings snapshot (filtered).
//! - Recent activity-log tail (caller-supplied — frontend reads from
//!   the in-memory store and passes a slice).
//! - Output-directory tree (depth-2, metadata only).
//!
//! ## Out of scope for Phase 1
//!
//! - Crash-report enumeration (Phase 2).
//! - Side-by-side redaction-preview UI (Phase 2 — review modal).
//! - Deep-link arming + session-window capture (Phase 3).

use serde::{Deserialize, Serialize};
use std::fs;
use std::path::Path;

use tauri::AppHandle;

/// Caller-supplied input for [`build_diagnostic_bundle`]. The
/// frontend assembles this struct from the in-memory stores (activity
/// log, dependency versions) so the backend doesn't have to reach
/// into Tauri-managed React state.
#[derive(Debug, Deserialize)]
pub struct DiagnosticBundleInput {
    /// Recent activity-log entries. Caller decides the slice (last N
    /// minutes, last K entries, …). Each line is already
    /// human-readable; the composer wraps them in a Markdown code
    /// block and applies path-username redaction.
    pub activity_log_lines: Vec<String>,
    /// Version strings for every tool the user has installed.
    /// Frontend supplies this from `getComponentVersions()`.
    pub component_versions: Vec<ComponentVersion>,
    /// Optional one-line summary the user typed when triggering the
    /// capture (e.g. "MV download failed for Anne-Marie album").
    /// Used as the issue title prefix.
    pub user_summary: Option<String>,
}

#[derive(Debug, Deserialize)]
pub struct ComponentVersion {
    pub name: String,
    pub version: String,
}

/// Result returned from [`build_diagnostic_bundle`]. The frontend
/// displays `markdown_body` in the review modal and uses
/// `github_issue_url` for the "Submit to GitHub" action.
#[derive(Debug, Serialize)]
pub struct DiagnosticBundle {
    /// Full Markdown body suitable for pasting into a GitHub issue.
    /// Already includes the redacted activity log, settings snapshot,
    /// version table, and output-dir listing.
    pub markdown_body: String,
    /// Pre-filled GitHub issue URL with the bundle as the body. The
    /// frontend opens this in the system browser via the shell
    /// plugin; the user clicks GitHub's own Submit button.
    pub github_issue_url: String,
    /// Total byte size of the rendered Markdown — surfaced to the
    /// review modal so users can see at a glance how big the bundle
    /// is before sharing.
    pub size_bytes: usize,
}

/// Build the diagnostic bundle (Phase 1 MVP).
///
/// Composes the full Markdown report and the corresponding GitHub
/// issue URL. Never reads file contents, never touches the keychain,
/// never auto-submits.
pub fn build_diagnostic_bundle(
    app: &AppHandle,
    input: DiagnosticBundleInput,
) -> Result<DiagnosticBundle, String> {
    let mut body = String::new();

    // --- Header ---
    body.push_str("## MeedyaDL Diagnostic Bundle\n\n");
    body.push_str("> Generated by MeedyaDL > Settings > Advanced > Diagnostics. ");
    body.push_str("Review the contents below before submitting. No credentials, ");
    body.push_str("file contents, or keychain material are included.\n\n");

    if let Some(summary) = input.user_summary.as_deref() {
        body.push_str(&format!("**User summary:** {}\n\n", summary.trim()));
    }
    body.push_str(&format!(
        "**Generated:** {}\n",
        chrono::Utc::now().to_rfc3339()
    ));
    body.push_str(&format!(
        "**MeedyaDL version:** {}\n",
        app.package_info().version
    ));
    body.push_str(&format!(
        "**OS:** {} ({})\n\n",
        std::env::consts::OS,
        std::env::consts::ARCH
    ));

    // --- Component versions ---
    body.push_str("### Component Versions\n\n");
    if input.component_versions.is_empty() {
        body.push_str("_(versions unavailable — frontend supplied empty list)_\n\n");
    } else {
        body.push_str("| Component | Version |\n|---|---|\n");
        for cv in &input.component_versions {
            body.push_str(&format!(
                "| {} | {} |\n",
                escape_pipe(&cv.name),
                escape_pipe(&cv.version)
            ));
        }
        body.push('\n');
    }

    // --- Settings snapshot (redacted) ---
    body.push_str("### Settings (redacted)\n\n");
    match collect_redacted_settings(app) {
        Ok(json) => {
            body.push_str("<details><summary>Click to expand</summary>\n\n```json\n");
            body.push_str(&json);
            body.push_str("\n```\n\n</details>\n\n");
        }
        Err(e) => {
            body.push_str(&format!("_(settings snapshot failed: {e})_\n\n"));
        }
    }

    // --- Output directory tree ---
    body.push_str("### Output Directory Structure\n\n");
    match collect_output_tree(app) {
        Some(tree) => {
            body.push_str("Depth-2 listing of the configured output path. Filenames + sizes only — no file contents.\n\n");
            body.push_str("<details><summary>Click to expand</summary>\n\n```\n");
            body.push_str(&tree);
            body.push_str("\n```\n\n</details>\n\n");
        }
        None => {
            body.push_str("_(no output path configured / not readable)_\n\n");
        }
    }

    // --- Activity log tail ---
    body.push_str("### Recent Activity Log\n\n");
    if input.activity_log_lines.is_empty() {
        body.push_str("_(no recent activity)_\n\n");
    } else {
        let count = input.activity_log_lines.len();
        body.push_str(&format!(
            "Last {count} entries (caller-supplied slice). Usernames in paths are redacted.\n\n"
        ));
        body.push_str("<details><summary>Click to expand</summary>\n\n```\n");
        for line in &input.activity_log_lines {
            body.push_str(&redact_path_usernames(line));
            body.push('\n');
        }
        body.push_str("\n```\n\n</details>\n\n");
    }

    // --- Final size sanity check + GitHub URL truncation ---
    const GITHUB_BODY_LIMIT: usize = 65_536;
    let issue_body = if body.len() > GITHUB_BODY_LIMIT {
        let head = &body[..GITHUB_BODY_LIMIT.saturating_sub(200)];
        format!(
            "{head}\n\n_(bundle truncated — original size {} bytes; copy the full markdown from the review modal if needed)_\n",
            body.len()
        )
    } else {
        body.clone()
    };

    let title = input
        .user_summary
        .as_deref()
        .map(|s| format!("[Diagnostic] {}", s.chars().take(80).collect::<String>()))
        .unwrap_or_else(|| "[Diagnostic] MeedyaDL diagnostic bundle".to_string());

    // Build the GitHub issue URL using the `url` crate's
    // form_urlencoded path (same pattern as crash_report_service so
    // every special char — backticks, newlines, pipes — is escaped
    // correctly).
    let mut issue_url =
        url::Url::parse("https://github.com/MWBMPartners/MeedyaDL/issues/new")
            .map_err(|e| format!("parse base url: {e}"))?;
    issue_url
        .query_pairs_mut()
        .append_pair("title", &title)
        .append_pair("body", &issue_body)
        .append_pair("labels", "diagnostic-bundle");

    Ok(DiagnosticBundle {
        size_bytes: body.len(),
        markdown_body: body,
        github_issue_url: issue_url.to_string(),
    })
}

/// Read settings.json from disk, parse, hard-filter every credential
/// field, and return the pretty-printed JSON as a String. Returns the
/// raw bytes on parse failure (better to show *something* in the
/// bundle than fail the capture).
fn collect_redacted_settings(app: &AppHandle) -> Result<String, String> {
    use crate::utils::platform::get_app_data_dir;
    let settings_path = get_app_data_dir(app).join("settings.json");
    let raw = fs::read_to_string(&settings_path)
        .map_err(|e| format!("read settings.json: {e}"))?;
    let mut value: serde_json::Value = match serde_json::from_str(&raw) {
        Ok(v) => v,
        Err(_) => return Ok(redact_path_usernames(&raw)),
    };
    redact_credential_fields(&mut value);
    let pretty =
        serde_json::to_string_pretty(&value).map_err(|e| format!("serialize: {e}"))?;
    Ok(redact_path_usernames(&pretty))
}

/// Walk a serde_json::Value and replace any value at a known
/// credential key with the literal `"<redacted>"` string. Operates
/// in-place. Keys we redact: anything containing "key", "token",
/// "cookie", "private", "wrapper_account_url", "musickit_team_id",
/// "musickit_key_id". Conservative — false positives just lose
/// information from the bundle, false negatives leak credentials.
fn redact_credential_fields(value: &mut serde_json::Value) {
    const SENSITIVE_SUBSTRINGS: &[&str] = &[
        "key",
        "token",
        "cookie",
        "private",
        "wrapper_account_url",
        "musickit_team_id",
        "musickit_key_id",
        "secret",
        "password",
    ];
    fn is_sensitive_key(key: &str) -> bool {
        let lower = key.to_lowercase();
        SENSITIVE_SUBSTRINGS
            .iter()
            .any(|needle| lower.contains(*needle))
    }
    match value {
        serde_json::Value::Object(map) => {
            for (k, v) in map.iter_mut() {
                if is_sensitive_key(k) {
                    *v = serde_json::Value::String("<redacted>".to_string());
                } else {
                    redact_credential_fields(v);
                }
            }
        }
        serde_json::Value::Array(arr) => {
            for v in arr.iter_mut() {
                redact_credential_fields(v);
            }
        }
        _ => {}
    }
}

/// Replace `/Users/{name}/…` and `/home/{name}/…` and Windows
/// `C:\Users\{name}\…` with `…/{user}/…` so the bundle doesn't leak
/// the operator's account name.
pub fn redact_path_usernames(input: &str) -> String {
    use std::sync::LazyLock;
    static UNIX: LazyLock<regex::Regex> = LazyLock::new(|| {
        regex::Regex::new(r"(/Users/|/home/)[^/\s\\]+").expect("unix regex")
    });
    static WIN: LazyLock<regex::Regex> = LazyLock::new(|| {
        regex::Regex::new(r"(?i)([A-Z]:\\Users\\)[^\\/\s]+").expect("win regex")
    });
    let after_unix = UNIX.replace_all(input, "${1}{user}").into_owned();
    WIN.replace_all(&after_unix, "${1}{user}").into_owned()
}

/// Read the configured output directory, walk to depth 2, return a
/// `tree(1)`-style ASCII listing. Returns `None` when no output path
/// is configured or the dir is unreadable.
fn collect_output_tree(app: &AppHandle) -> Option<String> {
    let settings = crate::services::config_service::load_settings(app).ok()?;
    if settings.output_path.is_empty() {
        return None;
    }
    let root = Path::new(&settings.output_path);
    if !root.exists() {
        return None;
    }
    let mut out = String::new();
    out.push_str(&redact_path_usernames(&format!("{}\n", root.display())));
    render_dir_tree(root, 0, &mut out, &mut 0);
    Some(out)
}

/// Recursive depth-bounded tree renderer. Caps at 200 entries total
/// to keep the bundle from ballooning on large music libraries.
fn render_dir_tree(dir: &Path, depth: usize, out: &mut String, count: &mut usize) {
    const MAX_DEPTH: usize = 2;
    const MAX_ENTRIES: usize = 200;
    if depth > MAX_DEPTH {
        return;
    }
    let entries = match fs::read_dir(dir) {
        Ok(it) => it,
        Err(_) => return,
    };
    let mut entries: Vec<_> = entries.flatten().collect();
    entries.sort_by_key(|e| e.file_name());
    let prefix = "  ".repeat(depth);
    for entry in entries {
        if *count >= MAX_ENTRIES {
            out.push_str(&format!("{prefix}…\n"));
            return;
        }
        *count += 1;
        let path = entry.path();
        let name = path
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("?")
            .to_string();
        if entry.file_type().map(|ft| ft.is_dir()).unwrap_or(false) {
            out.push_str(&format!("{prefix}{name}/\n"));
            render_dir_tree(&path, depth + 1, out, count);
        } else {
            let size = entry.metadata().map(|m| m.len()).unwrap_or(0);
            out.push_str(&format!("{prefix}{name} ({size} bytes)\n"));
        }
    }
}

/// Escape pipe chars in Markdown table cells.
fn escape_pipe(s: &str) -> String {
    s.replace('|', "\\|")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn redacts_username_in_paths() {
        let s = "Cookies at /Users/alice/Library/cookies.txt";
        let r = redact_path_usernames(s);
        assert_eq!(r, "Cookies at /Users/{user}/Library/cookies.txt");
    }

    #[test]
    fn redacts_linux_home_paths() {
        let s = "tmp dir: /home/bob/.cache/MeedyaDL";
        let r = redact_path_usernames(s);
        assert_eq!(r, "tmp dir: /home/{user}/.cache/MeedyaDL");
    }

    #[test]
    fn redacts_windows_user_paths() {
        let s = r"C:\Users\Charlie\AppData\Local\MeedyaDL\settings.json";
        let r = redact_path_usernames(s);
        assert_eq!(r, r"C:\Users\{user}\AppData\Local\MeedyaDL\settings.json");
    }

    #[test]
    fn redacts_credential_fields_in_settings_json() {
        let mut v: serde_json::Value = serde_json::json!({
            "output_path": "/Users/alice/Music",
            "musickit_team_id": "ABCD1234",
            "musickit_key_id": "XYZ987",
            "cookies_path": "/Users/alice/cookies.txt",
            "wrapper_account_url": "http://example/?token=secret",
            "use_wrapper": true,
            "language": "en-GB",
        });
        redact_credential_fields(&mut v);
        let obj = v.as_object().unwrap();
        assert_eq!(obj["musickit_team_id"], "<redacted>");
        assert_eq!(obj["musickit_key_id"], "<redacted>");
        assert_eq!(obj["cookies_path"], "<redacted>");
        assert_eq!(obj["wrapper_account_url"], "<redacted>");
        // Non-sensitive fields stay.
        assert_eq!(obj["use_wrapper"], true);
        assert_eq!(obj["language"], "en-GB");
        assert_eq!(obj["output_path"], "/Users/alice/Music");
    }

    #[test]
    fn nested_redaction_covers_per_service_settings() {
        let mut v: serde_json::Value = serde_json::json!({
            "per_service_settings": {
                "apple_music": {
                    "cookies_path": "/Users/alice/cookies.txt",
                    "preferred_engine": "gamdl",
                },
                "spotify": {
                    "auth_token": "topsecret",
                    "preferred_engine": "votify",
                }
            }
        });
        redact_credential_fields(&mut v);
        let am = &v["per_service_settings"]["apple_music"];
        assert_eq!(am["cookies_path"], "<redacted>");
        assert_eq!(am["preferred_engine"], "gamdl");
        let sp = &v["per_service_settings"]["spotify"];
        assert_eq!(sp["auth_token"], "<redacted>");
    }

    #[test]
    fn pipe_chars_in_table_cells_escaped() {
        assert_eq!(escape_pipe("foo|bar"), "foo\\|bar");
        assert_eq!(escape_pipe("no pipes"), "no pipes");
    }
}
