#!/bin/bash
# Copyright (c) 2024-2026 MeedyaSuite
# Licensed under the MIT License. See LICENSE file in the project root.
#
# Copyright Year Updater for MeedyaDL
# ======================================
#
# Updates the copyright end-year across the project's own source files
# to the current calendar year, producing a "2024-YYYY" range (2024 is
# when this project's first commit landed — see START_YEAR below). Run
# at the start of each new year to keep copyright notices current.
#
# Covers: Rust, TypeScript, CSS, Python, config (TOML/JSON/JS), the
# in-repo audit/help/scripts markdown that carries a real header,
# markdown, YAML, shell scripts, HTML, SVG, LICENSE, tauri.conf.json,
# and Entitlements.plist.
#
# Deliberately NOT covered, on purpose:
#   - THIRD_PARTY_LICENSES.md — holds VERBATIM upstream copyright
#     notices (GAMDL's "Copyright (c) 2024 Glomatico", GPAC's
#     "Copyright (c) Telecom ParisTech 2000-2025", etc.). Those are not
#     MeedyaDL's own copyright and must never be rewritten by this
#     script — the file is quoting someone else's legal text exactly.
#   - CONTRIBUTING.md / DEV_NOTES.md / .OpenAI/** — these describe the
#     copyright-header CONVENTION using the literal example string
#     ("Copyright (c) 2026 MeedyaSuite"). That string is documentation
#     about the rule, not an actual header instance; running this
#     script over them would corrupt the example text they're
#     explaining, not fix a real header.
#   - CHANGELOG.md — auto-generated by git-cliff; hand-editing it here
#     would just be overwritten on the next regeneration.
#   - Anything under node_modules/, dist/, or target/ (build output, not
#     source we own).
#
# Platform Note:
#   Auto-detects macOS vs Linux for correct `sed -i` syntax.
#
# Usage:
#   ./scripts/update-copyright-year.sh              # apply changes
#   ./scripts/update-copyright-year.sh --dry-run     # report only, changes nothing
#
# IMPORTANT: This script excludes itself from the bulk shell-script pass
# to avoid corrupting the regex patterns built below (which contain the
# literal text this script searches for). Its own copyright header
# (line 2) is updated separately, restricted to that one line.
#
# Whether this should run automatically: see the note at the bottom of
# this file's PR / commit description — short version, it's a once-a-
# year, low-stakes edit (nothing here is legally load-bearing on its
# own; MeedyaDL's actual copyright ownership doesn't change because a
# comment says so). A scheduled CI job that runs once a year and opens
# a PR is more machinery than a change this small and this rare
# justifies; running it by hand each January (or right before the first
# stable release of a new year) is simpler and just as reliable, as
# long as someone remembers to. If forgetting turns out to be the
# actual failure mode in practice, that argues for a January 1
# scheduled workflow that opens a PR for review — not for silently
# auto-committing.

set -euo pipefail

DRY_RUN=false
if [ "${1:-}" = "--dry-run" ] || [ "${1:-}" = "-n" ]; then
    DRY_RUN=true
fi

# --- Determine the current year and platform ---
CURRENT_YEAR=$(date +%Y)

if [ "$DRY_RUN" = true ]; then
    echo "Dry run — checking which files would move to copyright year: $CURRENT_YEAR (no files will be changed)"
else
    echo "Updating copyright year to: $CURRENT_YEAR"
fi

# Detect platform for correct sed in-place syntax
if [[ "$OSTYPE" == "darwin"* ]]; then
    SED_INPLACE=(sed -i '')
else
    SED_INPLACE=(sed -i)
fi

# The year this project's first commit landed (verified via
# `git log --reverse` — 2024-11-20). This is the START of every
# "2024-YYYY" range this script produces. It must never be the same as
# "whatever CURRENT_YEAR happens to be" — that was the bug that made a
# 2026 run of this script silently downgrade every accurate "2024-2026"
# header to a bare "2026", discarding the real start year.
START_YEAR=2024
if [ "$CURRENT_YEAR" = "$START_YEAR" ]; then
    YEAR_REPLACE="Copyright (c) ${START_YEAR}"
else
    YEAR_REPLACE="Copyright (c) ${START_YEAR}-${CURRENT_YEAR}"
fi

# Two independent patterns, both applied to every covered file:
#   - PATTERN_RANGE: rewrites an existing "YYYY-YYYY" range (the normal
#     case in every year after START_YEAR).
#   - PATTERN_SINGLE: rewrites a bare single "YYYY MeedyaSuite" header
#     (the shape a brand-new file, or a file from START_YEAR itself,
#     carries). This is the pattern the previous version of this script
#     built but never actually used — meaning almost every file in the
#     project, all of which currently use one of these two shapes,
#     would have been silently skipped.
# Neither pattern requires "MeedyaSuite" to follow a RANGE header
# (matching THIRD_PARTY_LICENSES.md's need to leave third-party ranges
# like "Copyright (c) 2002-2024 Axiomatic Systems, LLC" untouched is
# handled by never pointing this script at that file at all — see the
# "deliberately NOT covered" note above, not by a smarter regex).
PATTERN_RANGE="s/Copyright (c) 20[0-9][0-9]-[0-9][0-9][0-9][0-9]/${YEAR_REPLACE}/g"
PATTERN_SINGLE="s/Copyright (c) 20[0-9][0-9] MeedyaSuite/${YEAR_REPLACE} MeedyaSuite/g"

CHANGED_COUNT=0
UNCHANGED_COUNT=0
SELF_NAME="update-copyright-year.sh"

# Applies both patterns to one file. In normal mode, edits in place. In
# --dry-run mode, computes what the result WOULD be and only reports
# whether it differs — the file on disk is never touched either way.
process_file() {
    local file="$1"
    if [ ! -f "$file" ]; then
        return 0
    fi
    if [ "$DRY_RUN" = true ]; then
        local before after
        before=$(cat "$file")
        after=$(sed -e "$PATTERN_RANGE" -e "$PATTERN_SINGLE" "$file")
        if [ "$before" != "$after" ]; then
            echo "  would update: $file"
            CHANGED_COUNT=$((CHANGED_COUNT + 1))
        else
            UNCHANGED_COUNT=$((UNCHANGED_COUNT + 1))
        fi
    else
        # Compare before/after so the summary count is meaningful in
        # normal mode too, not just "ran on N files".
        local before
        before=$(cat "$file")
        "${SED_INPLACE[@]}" -e "$PATTERN_RANGE" -e "$PATTERN_SINGLE" "$file"
        if [ "$before" != "$(cat "$file")" ]; then
            CHANGED_COUNT=$((CHANGED_COUNT + 1))
        else
            UNCHANGED_COUNT=$((UNCHANGED_COUNT + 1))
        fi
    fi
}

process_tree() {
    # find ... -print0 | while read -d '' is the NUL-delimited pattern —
    # safe for filenames with spaces, and (unlike a bare -exec sed) lets
    # process_file do the before/after comparison for the summary count.
    local dir="$1"
    shift
    [ -d "$dir" ] || return 0
    while IFS= read -r -d '' f; do
        process_file "$f"
    done < <(find "$dir" "$@" -print0)
}

# --- Rust source files (.rs) ---
process_tree ./src-tauri/src -name "*.rs"

# --- Rust build script and root-level Cargo/Tauri config ---
for file in src-tauri/build.rs src-tauri/Cargo.toml src-tauri/deny.toml \
            src-tauri/tags.toml src-tauri/rust-toolchain.toml \
            src-tauri/tool-versions.toml src-tauri/tauri.conf.json \
            src-tauri/Entitlements.plist; do
    process_file "$file"
done

# --- TypeScript/TSX source files (.ts, .tsx) ---
process_tree ./src \( -name "*.ts" -o -name "*.tsx" \)

# --- CSS files (.css) ---
process_tree ./src -name "*.css"

# --- Root configuration files ---
for file in vite.config.ts vitest.config.ts tailwind.config.js postcss.config.js commitlint.config.js eslint.config.js cliff.toml; do
    process_file "$file"
done

# --- LICENSE file ---
process_file LICENSE

# --- Help documentation (.md), including translations under help/<lang>/ ---
process_tree ./help -name "*.md"

# --- Project root markdown files that carry a REAL header (not just
#     documentation describing the header convention — see the
#     "deliberately NOT covered" note at the top of this file) ---
for file in README.md Project_Plan.md; do
    process_file "$file"
done

# --- GitHub Actions workflow files (.yml) ---
process_tree ./.github/workflows -name "*.yml"

# --- GitHub Actions helper scripts (.py) ---
process_tree ./.github/scripts -name "*.py"

# --- Database schema files and release-note templates ---
#     These were missed until 2026-09: they carry a real header just like
#     every other source file, but their file types were not in this list,
#     so a run left them behind while reporting success. If you add a new
#     kind of file that carries a header, add it here too — nothing else
#     will notice that it was skipped.
process_tree ./src-tauri/src -name "*.sql"
process_tree ./.github -name "*.tera"

# --- Scripts: shell/JS/Python, excluding this file to prevent
#     self-corruption (see the special-cased line-2-only update below) ---
process_tree ./scripts \( -name "*.sh" -o -name "*.mjs" -o -name "*.js" -o -name "*.py" \) ! -name "$SELF_NAME"

# --- Audit-check scripts and their README (tools/audit-checks/) ---
process_tree ./tools -name "*.py"
process_file tools/audit-checks/README.md

# Update only line 2 of THIS script (the copyright header) without
# running the bulk patterns over its own body — those patterns are
# built from the literal text "Copyright (c) 20[0-9][0-9]..." above,
# and a global pass would match and corrupt that literal text instead
# of just the header. Both header shapes (range/single) are handled the
# same way as everywhere else, just restricted to line 2 via `2s/.../`.
if [ "$DRY_RUN" = true ]; then
    before=$(sed -n '2p' "./scripts/${SELF_NAME}")
    after=$(sed -e "2s/Copyright (c) 20[0-9][0-9]-[0-9][0-9][0-9][0-9]/${YEAR_REPLACE}/" \
                -e "2s/Copyright (c) 20[0-9][0-9] MeedyaSuite/${YEAR_REPLACE} MeedyaSuite/" \
                "./scripts/${SELF_NAME}" | sed -n '2p')
    if [ "$before" != "$after" ]; then
        echo "  would update: ./scripts/${SELF_NAME} (line 2)"
        CHANGED_COUNT=$((CHANGED_COUNT + 1))
    else
        UNCHANGED_COUNT=$((UNCHANGED_COUNT + 1))
    fi
else
    before=$(sed -n '2p' "./scripts/${SELF_NAME}")
    "${SED_INPLACE[@]}" \
        -e "2s/Copyright (c) 20[0-9][0-9]-[0-9][0-9][0-9][0-9]/${YEAR_REPLACE}/" \
        -e "2s/Copyright (c) 20[0-9][0-9] MeedyaSuite/${YEAR_REPLACE} MeedyaSuite/" \
        "./scripts/${SELF_NAME}"
    after=$(sed -n '2p' "./scripts/${SELF_NAME}")
    if [ "$before" != "$after" ]; then
        CHANGED_COUNT=$((CHANGED_COUNT + 1))
    else
        UNCHANGED_COUNT=$((UNCHANGED_COUNT + 1))
    fi
fi

# --- HTML entry point and other root files ---
for file in index.html .gitignore; do
    process_file "$file"
done

# --- SVG assets (includes assets/brand/ and the legacy assets/brand-old/) ---
process_tree ./assets -name "*.svg"

# --- Claude context files (including .claude/memory/) ---
process_tree ./.claude -name "*.md"

echo ""
if [ "$DRY_RUN" = true ]; then
    echo "Dry run complete: $CHANGED_COUNT file(s) would change, $UNCHANGED_COUNT already correct or not applicable."
    echo "Re-run without --dry-run to apply."
else
    echo "Copyright year updated to $CURRENT_YEAR: $CHANGED_COUNT file(s) changed, $UNCHANGED_COUNT already correct or not applicable."
fi
