/**
 * Copyright (c) 2024-2026 MeedyaDL
 * Licensed under the MIT License. See LICENSE file in the project root.
 *
 * @file src/vite-env.d.ts - TypeScript ambient declarations for Vite
 *
 * This is a TypeScript declaration file (`.d.ts`) that does not contain
 * any runtime code. It provides type information to the TypeScript compiler
 * about Vite-specific features that exist at runtime but have no TypeScript
 * definitions by default.
 *
 * The triple-slash reference directive below imports Vite's client-side
 * type definitions, which provide types for:
 *
 * 1. `import.meta.env` - Vite's environment variables object
 *    - `import.meta.env.DEV` (boolean): true during development
 *    - `import.meta.env.PROD` (boolean): true in production builds
 *    - `import.meta.env.MODE` (string): current build mode
 *    - `import.meta.env.VITE_*` (string): custom env variables
 *
 * 2. Static asset imports - allows importing non-JS files as modules:
 *    - `import logo from './logo.svg'` (returns URL string)
 *    - `import styles from './styles.module.css'` (CSS modules)
 *    - `import data from './data.json'` (JSON imports)
 *
 * 3. CSS/SCSS/Sass module type declarations
 *
 * 4. Web Worker imports (`import Worker from './worker?worker'`)
 *
 * This file is auto-generated by `npm create vite@latest` and should
 * generally not be modified manually. It must be included in the project's
 * `tsconfig.json` includes for the types to be recognized.
 *
 * @see {@link https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html} - Declaration files
 * @see {@link https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html} - Triple-slash directives
 * @see {@link https://vite.dev/guide/env-and-mode.html#intellisense-for-typescript} - Vite TS env types
 * @see {@link https://vite.dev/guide/features.html#client-types} - Vite client types
 */

/// <reference types="vite/client" />
